-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 22:07:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_epis` DEFAULT CHARACTER SET utf8 ;
USE `db_epis` ;

-- -----------------------------------------------------
-- Table `db_epis`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`colaboradores` (
  `id_colaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_colaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`epis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`epis` (
  `id_epi` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `codigo_barra` VARCHAR(255) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_epi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`emprestimos` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  `descricao` VARCHAR(255) NOT NULL,
  `quantidade` INT NOT NULL,
  `data_retirada` DATE NOT NULL,
  `data_devolucao` DATE NULL,
  `id_colaborador` INT NOT NULL,
  `id_epi` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimos_colaboradores1_idx` (`id_colaborador` ASC),
  INDEX `fk_emprestimos_epis1_idx` (`id_epi` ASC),
  CONSTRAINT `fk_emprestimos_colaboradores1`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `db_epis`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimos_epis1`
    FOREIGN KEY (`id_epi`)
    REFERENCES `db_epis`.`epis` (`id_epi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insersão de dados padrão no sistema

-- Usuários
INSERT INTO usuarios  (nome, email, senha) VALUES ('Administrador', 'admin@sistema.com', '123');